import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import '@rainbow-me/rainbowkit/styles.css';
import Providers from "./providers";
import NavBar from "@/components/layouts/NavBar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen gradient-bg-welcome`}
      >
          <Providers>
            <NavBar />
            {children}
          </Providers>
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              borderRadius: '10px',
              background: '#333',
              color: '#fff',
              maxWidth: '800px', // Add max width to prevent text overflow
              wordBreak: 'break-word' // Allow text to wrap
            },
            success: {
              duration: 3000,
            },
            error: {
              duration: 3000,
            },
          }}
        />
      </body>
    </html>
  );
}
